### ISSUE TITLE
Godot crashes on import of `starmap_16k.jpg` on Ubuntu

### ISSUE THREAD

**Issue by nicklecoder** [ivoyager/ivoyager-bugs#4]
I'm running Ubuntu 19.04 with Godot 3.1.1; Godot crashes every time I attempt to import the planetarium or base projects when the import reaches the `starmap_16k.jpg` file. Removing the file from the project seems to fix the import issue, but that file is important enough that it causes problems.

**Comment by charliewhitfield** [comment]
@nicklecoder, That's the largest image file in the project. I had some problems with this on my laptop until I reduced its size by applying higher compression. Can you post your computer specs, just for the record? We may have to determine what is "too big" by user trial-and-error.

If you have the ability to process jpg images, could you try compressing this to a smaller file or reducing the dimensions? If not, here is a really tiny version to try first: [starmap_1k.zip](https://github.com/ivoyager/ivoyager-bugs/files/3880189/starmap_1k.zip) (it's going to look awful). You will need to rename it to "starmap_16k.jpg" (or edit ivoyager/system_tree/voyager_environment.tscn) and add it to ivoyager_assets/starfields.

**Comment by nicklecoder** [comment]
I'll give it a shot. Mine is an HP Omen desktop, 7th gen i5-7400 processor with an NVIDIA GeForce GTX-1060 graphics card (not top of the line, but not an office machine either).

I'll try higher compression and see what happens.

**Comment by charliewhitfield** [comment]
On thinking about this, it seems like a Godot Engine problem if it is really crashing during import. I'm guessing Godot uses CPU only (not GPU), but image processing can be very memory intensive. Could that be the problem?

For the record, my laptop is XPS 13, i5-5200U, Intel HD Graphics 5500. I did expand memory to 4GB. I've learned to close everything else and walk away when importing the whole project. Maybe once or twice it failed and then I just tried again (it picks up wherever it was). But it does the job.

**Comment by nicklecoder** [comment]
Shrinking that image down so the larger dimension is 6000px did the trick, but it also makes the background lower-quality.

Which settings specifically did you set in Godot to increase memory to 4GB? My machine can definitely handle that, but I would prefer to have the full image as that does make a significant difference.

**Comment by nicklecoder** [comment]
Found the issue. By default, Godot 3.1.1 enables `Etc2` import, which I was told in IRC uses a lot of RAM. I disabled that and was able to import the entire image very quickly.
